FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY backend ./backend
COPY entrypoint.sh ./entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENV PYTHONPATH=/app

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["uv", "run", "uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]