services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend

    working_dir: /app

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

    env_file:
      - ../.env

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PYTHONPATH: /app
      RUN_MIGRATION: "true"

    command: uv run uvicorn backend.app.main:app --host 0.0.0.0 --port 8000

    volumes:
      - ../backend:/app/backend

    restart: unless-stopped

  worker:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend

    working_dir: /app

    depends_on:
      - postgres
      - redis

    env_file:
      - ../.env

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PYTHONPATH: /app
      RUN_MIGRATIONS: "false"

    command: uv run celery -A backend.app.workers.celery_app worker --loglevel=info

    volumes:
      - ../backend:/app/backend

    restart: unless-stopped

  postgres:
    image: postgres:16

    ports:
      - "5431:5432"

    env_file:
      - ../.env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7

    restart: unless-stopped

volumes:
  postgres_data: